version: "3.9"

services:
  php: 
    image: docker-push.wynd.eu/php:8.1-fpm
    volumes:
      - socket:/var/run/php-fpm/
      - ./:/var/www/html/
    env_file:
      - .env.local
    environment:
      PHP_OPCACHE_ENABLE: 
    # restart: always
  nginx: 
    image: docker-push.wynd.eu/nginx:1.22
    environment:
      UPSTREAM_SERVER: unix:/var/run/php-fpm/php-fpm.sock
    volumes:
      - socket:/var/run/php-fpm/
      - ./public:/var/www/html/public
      
    #Mapping du port 8080 dans mon container sur le port de mon local 8011 que l'on a définit
    ports:
      - 8011:80
    
    env_file:
      - .env.local
    # restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.training.rule=Host(`app.127.0.0.1.traefik.me`)
      - traefik.http.services.training.loadbalancer.server.port=80
      - traefik.http.routers.training.entrypoints=web

volumes:
  socket:
    driver: local

networks:
  default:
    external: true
    name: traefik
