name: Install

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  install:
    runs-on: ubuntu-latest

    env:
      COMPOSER_CACHE_DIR: "${{ github.workspace }}/.cache/composer"
      APP_ENV: "test"
      APP_DEBUG: "0"
      PHP_OPCACHE_ENABLE: "0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: |
            pdo
            mbstring
            exif
            pcntl

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php --filename=composer
          php -r "unlink('composer-setup.php');"
          chmod +x composer
          mv composer /usr/local/bin/

      - name: Install dependencies
        run: composer install --prefer-dist --optimize-autoloader --no-interaction
        working-directory: ${{ github.workspace }}

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}



